steps:
  - name: Check PHP mods installed.
    plugin: Script
    script: |
      php -v
      php -m
  - name: Install Drupal 7
    plugin: Drupal
    runInstall: true
    profileName: standard
    clearCaches: false
    subDirectory: docroot
    phpMods:
      - pgsql
      - pspell
      - recode
      - soap
  - name: Check PHP mods installed.
    plugin: Script
    script: |
      php -m
