steps:
  - name: Install Drupal 7
    plugin: Drupal
    runInstall: true
    profileName: standard
    clearCaches: false
    subDirectory: docroot
    phpConstants:
      DEVUSER: Developer
      EMAIL: dev@example.com
      constant_1: example_1
      CONSTANT_2: example_2
      _constant_3: example_3
      _CONSTANT_4: example_4
  - name: Test phpConstants.
    plugin: Script
    script: |
      cat <<EOT >> /var/www/html/constants-example.php
      <?php
        echo DEVUSER;
        echo EMAIL;
        echo constant_1;
        echo CONSTANT_2;
        echo _constant_3;
        echo _CONSTANT_4;
      ?>
      EOT
