steps:
  - name: Check PHP mods installed.
    plugin: Script
    script: |
      php -m
  - name: Install Drupal 7
    plugin: Drupal
    runInstall: true
    profileName: standard
    clearCaches: false
    subDirectory: docroot
    phpConstants:
      - php5.6-pgsql
      - php5.6-pspell
      - php5.6-recode
      - php5.6-soap
  - name: Check PHP mods installed.
    plugin: Script
    script: |
      php -m
